//
//  Constants.h
//  TOPIOSSdk
//
//  Created by fangweng on 12-11-17.
//
//

#import <Foundation/Foundation.h>

@interface TopConstants : NSObject

FOUNDATION_EXPORT NSString *const SELLER_PLATFORM_APPKEY;
FOUNDATION_EXPORT NSString *const SELLER_PLATFORM_CALLBACK;

FOUNDATION_EXPORT NSString *const PARAMETER_IS_RESPONSE;
FOUNDATION_EXPORT NSString *const PARAMETER_RESPONSE;
FOUNDATION_EXPORT NSString *const PARAMETER_SEQUENCE;
FOUNDATION_EXPORT NSString *const PARAMETER_EVENT;
FOUNDATION_EXPORT NSString *const PARAMETER_CALLBACKURL;

FOUNDATION_EXPORT NSString *const PARAMETER_APPKEY;
FOUNDATION_EXPORT NSString *const PARAMETER_UID;
FOUNDATION_EXPORT NSString *const PARAMETER_AUTHSTRING;
FOUNDATION_EXPORT NSString *const PARAMETER_CHATNICK;

FOUNDATION_EXPORT int const ASYN_CALL_TIMEOUT;

FOUNDATION_EXPORT  int const TRACKER_TYPE_EVENT; //事件类型
FOUNDATION_EXPORT  int const TRACKER_TYPE_EXCEPTION; //异常类型
FOUNDATION_EXPORT  int const TRACKER_TYPE_NOTIFY; //通知类型
FOUNDATION_EXPORT  int const TRACKER_TYPE_MODULE; //模块内部类型
FOUNDATION_EXPORT  int const TRACKER_TYPE_API;//服务调用

@end
