//
//  AppEvent.h
//  TOPIOSSdk
//
//  Created by fangweng on 12-11-21.
//
//

#import <Foundation/Foundation.h>

@interface TopAppEvent : NSObject

FOUNDATION_EXPORT NSString *const EVENT_SSO;
FOUNDATION_EXPORT NSString *const EVENT_GETLOGINUSERS;
FOUNDATION_EXPORT NSString *const EVENT_BACK_PLATFORM;
FOUNDATION_EXPORT NSString *const EVENT_GO_PLUGIN;
FOUNDATION_EXPORT NSString *const EVENT_ITEM_DETAIL;
FOUNDATION_EXPORT NSString *const EVENT_ITEM_LIST;
FOUNDATION_EXPORT NSString *const EVENT_TRADE_DETAIL;
FOUNDATION_EXPORT NSString *const EVENT_TRADE_LIST;
FOUNDATION_EXPORT NSString *const EVENT_REFUND_DETAIL;
FOUNDATION_EXPORT NSString *const EVENT_REFUND_LIST;
FOUNDATION_EXPORT NSString *const EVENT_WANGWANG_CHAT;
FOUNDATION_EXPORT NSString *const EVENT_MC_DETAIL;
FOUNDATION_EXPORT NSString *const EVENT_MC_LIST;

@end
